export const API_URL = ""
export const API_KEY = ""
export const BG_COLOR = "#111111"
export const INDEX_TITLE = ""
export const INDEX_DESCRIPTION = ""
export const HEADER_TITLE = ""
export const HEADER_DESCRIPTION = ""
